bantumin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path
from . import views 

app_name = 'core'

urlpatterns = [
    path('home/', views.formBantek, name='formBantek'),
    path('tiket/', views.tiketBantek, name='tiketBantek'),
    path('tiket/daftar/', views.daftarTiket, name='daftarTiket'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='user_logout'),
    path('delete/tiket/<int:tiket_id>/', views.deleteTiket, name='deleteTiket'),
    path('edit/tiket/<int:tiket_id>/', views.editTiket, name='editTiket')
]

core/models.py
from django.db import models

# Create your models here.

class Pegawai(models.Model):
    id_pegawai = models.AutoField(primary_key=True, null=False)
    NAMA = models.CharField(max_length=255, null=True)
    NIP = models.CharField(max_length=255, null=True)
    IP = models.CharField(max_length=255, null=True)
    JABATAN = models.FloatField(null=True)
    BIDANG = models.CharField(max_length=255, null=True)
    

class Tiket(models.Model):
    ID = models.AutoField(primary_key=True)
    NAMA = models.CharField(max_length=255, null=False)
    BIDANG = models.CharField(max_length=255, null=False)
    JENIS_MASALAH = models.CharField(max_length=255, null=False)
    PERMASALAHAN = models.TextField(null=False)
    DATE = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.NAMA} - {self.DATE.strftime("%d/%m/%Y")}'

core/forms.py
# forms.py
from django import forms
from .models import Pegawai, Tiket
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm



BANTEK_CHOICES =( 
    ("Pilih Jenis Masalah", "Pilih Jenis Masalah"), 
    ("Software", "Software"), 
    ("Hardware", "Hardware"), 
    ("Jaringan Internet/Intranet", "Jaringan Internet/Intranet"), 
    ("Join Domain", "Join Domain"), 
    ("Permintaan Data", "Permintaan Data"), 
)

BIDANG_CHOICES =( 
    ("Pilih Bidang", "Pilih Bidang"), 
    ("Umum", "Umum"), 
    ("DP3", "DP3"), 
    ("KBP", "KBP"), 
    ("P2 Humas", "P2 Humas"), 
    ("PPIP", "PPIP"),
    ("PEP", "PEP"), 
)


class BantuanTeknisForm(forms.Form):
    nama = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'border p-2 rounded-md', 'style': 'height: 40px;'}),
        required=True,
        label='Nama',
    )
    bidang = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'border w-80 p-2 rounded-md'}),
        required=True,
        label='Bidang',
        choices=BIDANG_CHOICES,
    )
    jenis_permasalahan = forms.ChoiceField(
        choices=BANTEK_CHOICES,
        label='Jenis Masalah',
        widget=forms.Select(attrs={'class': 'border w-80 p-2 rounded-md'}),
    )
    permasalahan = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'border p-2 rounded-md', 'style': 'height: 100px;'}),
        required=True,
        label='Permasalahan',
    )



class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'NIP Bapak/Ibu',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
        
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': ' Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class TiketForm(forms.ModelForm):
    class Meta:
        model = Tiket
        exclude = ['DATE']

core/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .models import Pegawai, Tiket
from .forms import BantuanTeknisForm, LoginForm, TiketForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse





# Create your views here.

def index(request):
    return render(request, "core/index.html")

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, 'Berhasil login.')
                return redirect('core:formBantek')  # Ganti dengan URL redirect yang diinginkan

            else:
                messages.warning(request, 'username atau password Anda salah')
                return redirect('core:login_view')
    else:
        form = LoginForm()

    return render(request, 'core/login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        nama = request.POST['nama']
        password = request.POST['password']

        # Buat pengguna baru
        user = User.objects.create_user(username=username, nama=nama, email=email, password=password)
        user.first_name = nama
        user.save()

        # # Otentikasi pengguna dan login setelah registrasi
        # user = authenticate(username=username, password=password)
        # login(request, user)

        return redirect('core:formBantek')

    return render(request, 'core/register.html')

def user_logout(request):
    logout(request)
    messages.success(request, 'Berhasil logout.')
    return redirect('core:login_view')


def formBantek(request):
    form = BantuanTeknisForm()
    context = {
        'form': form,
    }

    return render(request, 'core/index.html', context)

def tiketBantek(request):
    if request.method == 'POST':
        form = BantuanTeknisForm(request.POST)

        if form.is_valid():
            nama = form.cleaned_data.get('nama', '')
            bidang = form.cleaned_data.get('bidang', '')
            jenis_masalah = form.cleaned_data.get('jenis_permasalahan', '')
            permasalahan = form.cleaned_data.get('permasalahan', '')

            # Simpan data di model
            tiket = Tiket(NAMA=nama, BIDANG=bidang, JENIS_MASALAH=jenis_masalah, PERMASALAHAN=permasalahan)
            tiket.save()

            return redirect('core:daftarTiket')
        else:
            # Handle the case when the form is not valid
            print(form.errors)  # Print form errors to the console for debugging
    else:
        form = BantuanTeknisForm()

def daftarTiket(request):
    tiket_list = Tiket.objects.all()
    items_per_page = 10
    paginator = Paginator(tiket_list, items_per_page)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'core/tiket.html', {'tiket_list': page_obj})

def deleteTiket(request, tiket_id):
    context = {}
    obj = get_object_or_404(Tiket, ID = tiket_id)
    if request.method == 'POST':
        obj.delete()
        return HttpResponseRedirect("/home")
    
    return render(request, "core/hapustiket.html", {'tiket': obj})

def editTiket(request, tiket_id):
    tiket = get_object_or_404(Tiket, pk=tiket_id)

    if request.method == 'POST':
        form = TiketForm(request.POST, instance=tiket)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:daftarTiket'))  # Ganti dengan URL yang sesuai
    else:
        form = TiketForm(instance=tiket)

    return render(request, 'core/edittiket.html', {'form': form, 'tiket': tiket})

core/templates/core/base.html
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
        <title>Bantek 050 2024</title>
    </head>
    <body class="bg-zinc-50">
        {% include 'core/navbar.html' %}


        {% block content %}
        {% endblock %}

        {% include 'core/footer.html' %}
    </body>
</html>

core/templates/core/edittiket.html
<!-- edit_tiket.html -->
{% extends 'core/base.html' %}

{% block content %}
  <h1 class="text-xl font-semibold mt-20 text-center pt-2">Edit Tiket</h1>
  <div class="max-w-2xl mx-auto bg-white p-8 rounded-md shadow-md mt-2">
    <form method="post" class="space-y-4">
      {% csrf_token %}
      
      <div>
        <label for="{{ form.NAMA.id_for_label }}" class="block text-sm font-semibold mb-2">Nama</label>
        {{ form.NAMA }}
      </div>

      <div>
        <label for="{{ form.BIDANG.id_for_label }}" class="block text-sm font-semibold mb-2">Bidang</label>
        {{ form.BIDANG }}
      </div>

      <div>
        <label for="{{ form.JENIS_MASALAH.id_for_label }}" class="block text-sm font-semibold mb-2">Jenis Masalah</label>
        {{ form.JENIS_MASALAH }}
      </div>

      <div class="border rounded-md p-2">
        <label for="{{ form.PERMASALAHAN.id_for_label }}" class="block text-sm font-semibold mb-1">Permasalahan</label>
        {{ form.PERMASALAHAN }}
      </div>

      <div class="flex items-center">
        <button type="submit" class="bg-teal-600 text-white py-2 px-4 rounded-md hover:bg-teal-900">Simpan Perubahan</button>
        <a href="{% url 'core:daftarTiket' %}" class="text-gray-600 ml-2 hover:text-gray-800">Batal</a>
      </div>
    </form>
  </div>
{% endblock %}

core/templates/core/footer.html
<footer class="absolute bottom-0 w-full bg-white text-center text-sm py-4">
    <button type="button" onclick="toggleNightMode()">Night Mode - AMC 050</button>
</footer>

core/templates/core/hapustiket.html
{% extends 'core/base.html' %}

{% block content %}

<div class="max-w-2xl mx-auto mt-20 p-4">
  <h2 class="text-xl font-semibold text-center py-2">Apakah Anda yakin ingin menghapus tiket berikut?</h2>

  <div class="flex bg-white p-4 rounded-md shadow-md mt-2">
      <div class="w-1/2 pr-8">
          <p class="text-sm"><span class="font-semibold">Nama:</span> {{ tiket.NAMA }}</p>
          <p class="text-sm"><span class="font-semibold">Bidang:</span> {{ tiket.BIDANG }}</p>
          <p class="text-sm"><span class="font-semibold">Jenis Masalah:</span> {{ tiket.JENIS_MASALAH }}</p>
          <p class="text-sm"><span class="font-semibold">Permasalahan:</span> {{ tiket.PERMASALAHAN }}</p>
          <p class="text-sm"><span class="font-semibold">Tanggal:</span> {{ tiket.DATE }}</p>
      </div>

      <div class="w-1/2">
          <form method="post" action="{% url 'core:deleteTiket' tiket.ID %}">
              {% csrf_token %}
              <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600">Hapus</button>
              <button type="button" onclick="window.history.back()" class="bg-teal-500 text-white px-4 py-2 rounded-md hover:bg-teal-600">Batal</button>
            </form>
      </div>
  </div>
</div>


{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}

<section id="home">
    <div class="flex justify-center items-center h-screen">

            <div class="">
                <h1 class="text-base font-semibold text-teal-600 md:text-xl lg:text-2xl">Form
                    <span class="mt-1 text-4xl block font-bold text-cyan-600">Bantumin 050</span>
                </h1>
                <h2 class="font-medium text-slate-500 text-lg mb-5">Bantuan Teknis Komputer dan Data  <br>
                    <span class="text-slate-900 lg:text-sm">Bidang Data dan Pengawasan Potensi Perpajakan</span>
                </h2>
                <p class="font-medium text-slate-400 mb-10 leading-relaxed">
                    Sinergi Kuat, Sumbarja Hebat, Kanwil 050 melesat,
                    <span class="text-slate-900 font-bold">Kanwil 050 Melesat</span>
                </p>
            </div>

            <div class="ml-4 mt-6">
                <div class="form-container bg-gray-200">
                    <form method="post" action="{% url 'core:tiketBantek' %}" class="">
                        {% csrf_token %}
                        {{ form.as_p|safe }}

                        <div class="flex justify-center">
                            <button type="submit" class="flex mt-2 py-2 px-8 text-sm bg-teal-600 
                            text-white rounded-xl hover:bg-teal-900 mx-2">Lapor</button>
                            <button type="reset" class="flex mt-2 py-2 px-8 text-sm bg-rose-600 
                            text-white rounded-xl hover:bg-rose-900 mx-2">Reset</a>
                        </div>
                        
                    </form>
                </div>
            </div>
       
    </div>
</section>

{% comment %} <script>
    $(document).ready(function () {

        $("#id_bidang_field").change(function () {
            var selectedBidang = $(this).val();
            var namaFieldSelect = $("#id_nama_field");

            namaFieldSelect.find("option").filter(function () {
                return $(this).data("bidang") !== selectedBidang;
            }).remove();
        });
    });
</script> {% endcomment %}


<script>
    function toggleNightMode() {
        document.body.classList.toggle('night-mode');
        document.querySelector('.form-container').classList.toggle('night-mode');
    }
</script>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In {% endblock %}

{% block content %}

{% comment %} coldplayKID@ {% endcomment %}


<div class='w-1/2 my-6 mt-20 mx-auto p-6 bg-gray-100 rounded-xl flex items-center'>
    <div class="w-full">
        <h2 class="text-2xl font-semibold mb-4">Login</h2>
        <form method="post" action="{% url 'core:login_view' %}" class="space-y-4">
            {% csrf_token %}

            <div>
                <label for="nip" class="block text-sm font-medium text-gray-600">Username:</label>
                <input type="text" id="nip" name="nip" required class="mt-1 p-2 w-full border rounded-md">
            </div>

            <div>
                <label for="password" class="block text-sm font-medium text-gray-600">Password:</label>
                <input type="password" id="password" name="password" required class="mt-1 p-2 w-full border rounded-md">
            </div>

            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-md">Login</button>
        </form>
    </div>
</div>


<div class='w-1/2 my-6 mx-auto p-4 bg-slate-400 hover:bg-slate-900 rounded-xl text-white'>
    <h3 class="text-center"><a href="{% url 'core:register' %}">Belum ada akun? Silakan register dulu</a><br> <h3>
</div>

{% endblock %}

core/templates/core/navbar.html
<!-- component -->
{% load static %}

<nav class="fixed top-0 px-3 py-3 flex justify-between items-center bg-gray-100 w-full z-10">
    <a class="text-3xl font-bold leading-none" href="#">
        <img class="w-16 md:w-20 lg:w-32" src="{% static 'img/logo.png' %}" alt="logo">
    </a>
    <p class="ml-4 text-sm font-semibold">Service Desk 050</p>
		<ul class="hidden absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 lg:flex lg:mx-auto lg:flex lg:items-center lg:w-auto lg:space-x-6">
			<li><a href="{% url 'core:formBantek' %}" class={% if  'home/' in request.path %} "text-sm text-blue-600 font-bold" {% else %} "text-gray-400 hover:text-gray-700 text-sm font-medium" {% endif %}>Home</a></li>
			<li class="text-gray-300">
				<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" class="w-4 h-4 current-fill" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
				</svg>
			</li>
			<li><a href="{% url 'core:daftarTiket' %}" class={% if  '/tiket/daftar/' in request.path %} "text-sm text-blue-600 font-bold" {% else %} "text-gray-400 hover:text-gray-700 text-sm font-medium" {% endif %}>Tiket</a></li>
			<li class="text-gray-300">
				<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" class="w-4 h-4 current-fill" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
				</svg>
			</li>
			<li><a class="text-sm text-gray-400 hover:text-gray-700" href="#">Katalog Layanan</a></li>
		</ul>
</nav>

core/templates/core/register.html
{% extends 'core/base.html' %}

{% block title %}Log In {% endblock %}

{% block content %}


<div class='w-1/2 my-6 mt-10 mx-auto p-6 bg-gray-100 rounded-xl flex items-center'>
    <div class="w-full">
        <h2 class="text-2xl font-semibold mb-4">Register</h2>
        <form method="post" action="{% url 'core:register' %}" class="space-y-4">
            {% csrf_token %}

            <div>
                <label for="nama" class="block text-sm font-medium text-gray-600">Nama:</label>
                <input type="text" id="nama" name="nama" required class="mt-1 p-2 w-full border rounded-md">
            </div>

            <div>
                <label for="nip" class="block text-sm font-medium text-gray-600">Username(NIP):</label>
                <input type="text" id="username" name="username" required class="mt-1 p-2 w-full border rounded-md">
            </div>

            <div>
                <label for="email" class="block text-sm font-medium text-gray-600">Email:</label>
                <input type="email" id="email" name="email" required class="mt-1 p-2 w-full border rounded-md">
            </div>

            <div>
                <label for="password" class="block text-sm font-medium text-gray-600">Password:</label>
                <input type="password" id="password" name="password" required class="mt-1 p-2 w-full border rounded-md">
            </div>

            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-md">Register</button>
        </form>
    </div>
</div>

<div class='w-1/2 my-3 mx-auto p-2 bg-slate-400 hover:bg-slate-900 rounded-xl text-white'>
    <h3 class="text-center"><a href="{% url 'core:login_view' %}">Sudah ada akun? Silakan login dulu</a><br> <h3>
</div>

{% endblock %}

core/templates/core/tiket.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<h1 class="text-xl font-semibold mt-20 text-center pt-2">Daftar Tiket</h1>
<div class="flex max-w-7xl mx-auto bg-white p-3 rounded-md shadow-md mt-2">
    <div class="w-1/4 pr-4 pl-1 py-5">
        <!-- Menu Filter -->
        <div class="bg-zinc-100 p-4 rounded-md shadow-md mb-5">
            <h2 class="text-lg font-semibold mb-2">Filter Tiket</h2>
            <div class="mb-4">
                <label for="jenisPermasalahan" class="block text-sm font-semibold mb-2">Jenis Permasalahan</label>
                <select id="jenisPermasalahan" class="w-full border p-2" onchange="filterData()">
                    <option value="all">All</option>
                    <option value="Software">Software</option>
                    <option value="Hardware">Hardware</option>
                    <option value="Jaringan Internet/Intranet">Jaringan Internet/Intranet</option>
                    <option value="Join Domain">Join Domain</option>
                    <option value="Permintaan Data">Permintaan Data</option>
                </select>

                <label for="tanggalTiket" class="block text-sm font-semibold mb-2 pt-2">Tanggal Tiket</label>
                <input type="date" id="tanggalTiket" class="w-full border p-2">

                <!-- <button type="button" onclick="filterData()" class="mt-4 bg-teal-600 text-white py-2 px-4 rounded-md hover:bg-teal-900">Filter</button> -->
            </div>            
        </div>
    </div>

    <div class="w-3/4">
        <table id="data-table" class="min-w-full bg-white border border-gray-300 shadow-sm text-sm">
            <thead>
                <tr class="bg-teal-600 text-white">
                    <th class="py-2 px-4 border-b border-r">Nama</th>
                    <th class="py-2 px-4 border-b border-r">Bidang</th>
                    <th class="py-2 px-4 border-b border-r">Jenis Masalah</th>
                    <th class="py-2 px-4 border-b border-r">Permasalahan</th>
                    <th class="py-2 px-4 border-b">Tanggal</th>
                    <th class="py-2 px-4 border-b">Status Tiket</th>
                    <th class="py-2 px-4 border-b">Tindak Lanjut</th>
                    <th class="py-2 px-4 border-b">Respon Adsis</th>
                </tr>
            </thead>
            <tbody>
                {% for tiket in tiket_list %}
                    <tr>
                        <td class="py-2 px-4 border-b border-r">{{ tiket.NAMA }}</td>
                        <td class="py-2 px-4 border-b border-r">{{ tiket.BIDANG }}</td>
                        <td class="py-2 px-4 border-b border-r">{{ tiket.JENIS_MASALAH }}</td>
                        <td class="py-2 px-4 border-b border-r">{{ tiket.PERMASALAHAN }}</td>
                        <td class="py-2 px-4 border-b">{{ tiket.DATE|date:"d/m/Y" }}</td>
                        <td class="py-2 px-4 border-b">Sedang diproses</td>
                        <td class="py-2 px-4 border-b border-r hover:text-red-500">
                        <a class="text-3xl font-bold leading-none" href="{% url 'core:deleteTiket' tiket.ID %}">
                            <img class="w-3 md:w-5 lg:w-7 mx-auto" src="{% static 'img/trash.png' %}" alt="logo">
                        </a>
                        <a class="text-3xl font-bold leading-none" href="{% url 'core:editTiket' tiket.ID %}">
                            <img class="w-3 md:w-5 lg:w-7 mx-auto" src="{% static 'img/pen.png' %}" alt="logo">
                        </a></td>
                        <td class="py-2 px-4 border-b"></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="pagination">
            <span class="step-links">
                {% if tiket_list.has_previous %}
                    <a href="?query={{ request.GET.query|urlencode }}&page=1">&laquo; first</a>
                    <a href="?query={{ request.GET.query|urlencode }}&page={{ tiket_list.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ tiket_list.number }} of {{ tiket_list.paginator.num_pages }}.
                </span>
        
                {% if tiket_list.has_next %}
                    <a href="?query={{ request.GET.query|urlencode }}&page={{ tiket_list.next_page_number }}">next</a>
                    <a href="?query={{ request.GET.query|urlencode }}&page={{ tiket_list.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>

</div>

<script>
    function filterData() {

        var filter = document.getElementById('jenisPermasalahan').value;
        var table = document.getElementById('data-table');
        var rows = table.getElementsByTagName('tr');

        for (var i = 1; i < rows.length; i++) {
            var category = rows[i].getElementsByTagName('td')[2].textContent;

            if (filter === 'all' || category === filter) {
                rows[i].style.display = '';
                } else {
                rows[i].style.display = 'none';
                }
            }
    }
</script>

{% endblock %}